[build-system]
requires = ["flit_core==3.12.0"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[project]
name = "bspp"
version = "1.0.3"
dependencies = ["pycryptodome==3.23.0"]
module = "bspp"
author = "Zsolt Mészárovics"
author-email = "zsolt@meszarovics.me"
home-page = "https://github.com/zsoltm/bspp"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3"
]
description = "Quake 3 .PK3 map info and BSP Parser"
requires-python=">=3.14"

[project.optional-dependencies]
dev = ["ruff==0.16.5", "ty==0.0.72", "flit==4.0.2"]

[tool.uv]
exclude-newer = "7d"
