[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line_length = 120
target-version = ['py311']

[project]
name = "bspp"
version = "1.0.2"
dependencies = ["pycryptodome==3.23.0"]
module = "bspp"
author = "Zsolt Mészárovics"
author-email = "zsolt@meszarovics.me"
home-page = "https://github.com/zsoltm/bspp"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3"
]
description = "Quake 3 .PK3 map info and BSP Parser"
requires-python=">=3.11"

[project.optional-dependencies]
dev = ["black==20.8b1", "flit>=3.0.0,<4", "pylint==2.6.0", "mypy==0.790"]
